### ISSUE TITLE
Airplane start position is off screen

### ISSUE THREAD

**Issue by varyndev** [VarynInc/game-experiments#11]
New airplanes should start off-screen and fly across the screen. Airplanes should always be moving. this will require several changes in parallel:

1. create a new function to compute the starting position of an airplane, the parameter to this function is an airplane object.
   ```javascript
   function setStartPosition(airplane) {
       let startX = random position off screen;
       let startY = random position off screen;
       airplane.x = startX;
       airplane.y = startY;
   ```
2. The start position should be off-screen. For now just select a random X and random Y off-screen, so either < 0 or > width/height.
3. airplane should be always moving. For now, just tween the airplane to a random X/Y position off the opposite side of the screen from the start position.

**Comment by DarkMatters** [comment]
Completed in #11
