### ISSUE TITLE
Improvements to airplane start

### ISSUE THREAD

**Issue by varyndev** [VarynInc/game-experiments#62]
there are still some bugs/issues with new planes:

1. sometimes they start but too close to another plane, and then crash before the user can deal with it. Add some logic to `airplane.setStartPosition` to determine if the new plane is too close to any current planes.
2. `active` is still not right, planes are active yet they are still off-screen. planes should not be come active (so they can crash) until they are fully visible on screen.

**Comment by varyndev** [comment]
@ansmor make sure you first pull the boss level PR, as that commit completely rewrites the logic for spawning

**Comment by DarkMatters** [comment]
will address when moved to gameframe
