### ISSUE TITLE
Separate function to create a plane

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/game-experiments#7]
Current code creates the airplane sprite in-line.  Factor out the airplane creation code into a separate function. Instead of a global `airplane` variable, use an array, since when we get this working as a game there will be more than one airplane active at a time and we need to keep track of all of them.

**Comment by varyndev** [comment]
Create the airplane sprite and set the registration point:

```javascript
        const airplane = new createjs.Bitmap(loader.getResult("airplane"));
        airplane.regX = airplane.image.width * 0.5;
        airplane.regY = airplane.image.height * 0.5;
        airplane.angle = 0;
        arrayOfPlanes.push(airplane);
        return airplane;
```

**Comment by varyndev** [comment]
Completed in #6
