### ISSUE TITLE
Change animation speed

### ISSUE THREAD

**Issue by varyndev** [VarynInc/game-experiments#9]
Currently the airplane moves too fast. set a slower speed constant to slow down a bit.

```
speedConst = 3; // lower = faster plane travel
```

make speed a property of the airplane. this would allow us to have different speeds for different airplanes.

**Comment by varyndev** [comment]
To complete this issue:

1. change animation speed to 15
2. move `speedConst` to the global section at the top, since (at the moment) it is const for all airplanes.

**Comment by DarkMatters** [comment]
See PR #13, I took a different approach. the speed is now a property of the airplane object. this will allow us to support different speeds for different planes.
